### ISSUE TITLE
secrets-store-csi-driver-aws not working

### ISSUE THREAD

**Issue by zestrells** [particuleio/terraform-kubernetes-addons#1234]
## Describe the bug

When I enable `secrets-store-csi-driver-aws` and deploy it with terragrunt, it looks to be deployed.
But when I do `kubectl get csidriver` I do not get the secrets-csi in the output for the kube-system namespace.

I currently only have this enabled below:
```
  secrets-store-csi-driver-aws = {
    enabled = true
  }
  ```

Do I need to also enable the non-aws csi driver to get it deployed in my EKS cluster and working?

```
  secrets-store-csi-driver = {
    enabled = true
  }
  ```

@ArchiFleKs

**Comment by ArchiFleKs** [comment]
@zestrells yes I think it is a dependency issue as when secrets-store-csi-driver is enable the AWS provider is automatically enabled by not the other way around. 

It might need some rework. In the mean time. Enabling secrets-store-csi-driver manually should solve the issue and create the CRDs

**Comment by zestrells** [comment]
Ahh I see, one other issue I am seeing is a failure to install `secrets-store-csi-driver`. I think this may be because upstream got changed, OR the main branch got changed from `master` -> `main`

```
│ Error: could not download chart: looks like "https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/index.yaml : 404 Not Found
```

**Comment by zestrells** [comment]
Created this PR - https://github.com/particuleio/terraform-kubernetes-addons/pull/1235

**Comment by ArchiFleKs** [comment]
> Created this PR - https://github.com/particuleio/terraform-kubernetes-addons/pull/1235 @ArchiFleKs 

Thanks. Could you test on main branch and if it is ok I'll create a release tomorrow

**Comment by zestrells** [comment]
Hey @ArchiFleKs , just confirmed main branch works.
```
➜ kubectl get csidriver
NAME                       ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
ebs.csi.aws.com            true             false            false             <unset>         false               Persistent   16h
efs.csi.aws.com            false            false            false             <unset>         false               Persistent   16h
secrets-store.csi.k8s.io   false            true             false             <unset>         false               Ephemeral    2m3s
```

**Comment by ArchiFleKs** [comment]
Fixed in https://github.com/particuleio/terraform-kubernetes-addons/releases/tag/v8.2.1
