### ISSUE TITLE
[bug] Issue with loki-stack due loki 3.x upgrade

### ISSUE THREAD

**Issue by giany** [particuleio/terraform-kubernetes-addons#1379]
## Describe the bug

After upgrading loki to 3.x I get the followWhen using 2.16.0 everything seems to be fine.

## What is the current behavior?

Using Loki 3.x I get the following error:

```
╷
│ Error: cannot patch "loki" with kind Ingress: Ingress.extensions "loki" is invalid: spec.rules[0].host: Invalid value: "map[host:logz.stg.xxxx.com paths:[/]]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
│
│   with helm_release.loki-stack[0],
│   on loki-stack.tf line 136, in resource "helm_release" "loki-stack":
│  136: resource "helm_release" "loki-stack" {
```

## What's the expected behavior?

Apply should work.

## Environment details

* Affected module version: 3.0.3 (happens with 3.0.0/3.0.1 as well)
* OS: MacOS
* Terraform version:  1.2.8
* Kubernetes version: EKS 1.22

**Comment by ArchiFleKs** [comment]
Hi @giany thanks for the heads up, this might be due to https://github.com/grafana/loki/tree/main/production/helm/loki, also a lots of changes are included in loki 3 that I missed. Please pin with a version < 3 for now, I'm planning on testing the loki upgrade end of next week.

**Comment by giany** [comment]
> Hi @giany thanks for the heads up, this might be due to https://github.com/grafana/loki/tree/main/production/helm/loki, also a lots of changes are included in loki 3 that I missed. Please pin with a version < 3 for now, I'm planning on testing the loki upgrade end of next week.

Thanks, already did that.

**Comment by ArchiFleKs** [comment]
Fixed in version >=10
