### ISSUE TITLE
[bug] helm provider issue

### ISSUE THREAD

**Issue by giany** [particuleio/terraform-kubernetes-addons#1500]
## Describe the bug

When using latest version of helm provider (2.7.1) I get this message:

```
│ Error: unable to build kubernetes objects from current release manifest: unable to recognize "": Get "https://xxxxx.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp: lookup xxxxxx.gr7.us-east-1.eks.amazonaws.com on 192.168.1.1:53: no such host
│
│   with helm_release.kube-prometheus-stack[0],
│   on kube-prometheus.tf line 462, in resource "helm_release" "kube-prometheus-stack":
│  462: resource "helm_release" "kube-prometheus-stack" {
```

Note that this has been happening for a while..the latest helm provider version that works for me is 2.4.1. 

## Environment details

* Affected module version: > 2.4.1
* OS: MacOS 
* Terraform version: 1.2.8
* Kubernetes version: 1.23

Any hints what could the issue be?

**Comment by ArchiFleKs** [comment]
@giany Hi and thanks, seems to me like a transcient issue based on your connection and not related to helm provider. Based on your log you failed to resolved the IP of your EKS control plane

**Comment by giany** [comment]
Can be closed..for some reason this does not happen anymore. Odd.
