### ISSUE TITLE
[enhancement] velero and restic config and support

### ISSUE THREAD

**Issue by dejwsz** [particuleio/terraform-kubernetes-addons#1518]
**Is your feature request related to a problem? Please describe.**
We cannot see any configuration for restic in Velero, is it supported? For AWS EFS you do not have snapshots so restic must be used for this

**Describe the solution you'd like**
Additional configuration for adding restic backups in Velero for EFS volumes while snapshots should be used for CSI based only.

**Describe alternatives you've considered**
Not yet any.

**Additional context**
Velero cannot backup properly any project which use EFS based PVC in EKS.

**Comment by dejwsz** [comment]
In the official chart they have restic related configurations:
https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

**Comment by dejwsz** [comment]
docs about restic extension: https://velero.io/docs/v1.9/restic/

**Comment by dejwsz** [comment]
OK, I can see it can be set by tweaking extra values like to apply source helm settings:

``` 
  ... 
  velero = {
    enabled                 = true
    extra_values            = <<EXTRA_VALUES
# Whether to deploy the restic daemonset.
deployRestic: true
# Set true for backup all pod volumes without having to apply annotation on the pod when used restic Default: false
defaultVolumesToRestic: false
EXTRA_VALUES
  }
```

**Comment by dejwsz** [comment]
it can be closed I think then

**Comment by ArchiFleKs** [comment]
Yes you can customize all the charts with the `extra_values` parameters. Feel free to close if that solved your issue
