### ISSUE TITLE
[bug] latest version of Velero 1.9.2 contains bug

### ISSUE THREAD

**Issue by dejwsz** [particuleio/terraform-kubernetes-addons#1525]
Just for the record:

https://github.com/vmware-tanzu/velero/issues/5438

Next release 1.9.3 should fix it, current addons contain it and it can make your velero backups fail - at least in AWS.

**Comment by dejwsz** [comment]
1.9.3 fixed version is already available

**Comment by ArchiFleKs** [comment]
@dejwsz closing as new version is available in latest releases
