### ISSUE TITLE
feature: Cortex

### ISSUE THREAD

**Issue by apmartins85** [particuleio/terraform-kubernetes-addons#19]
Hi folks, hope you are doing great! 
First, congrats for the awesome project! Have you considered to add cortex as addon to work with prometheus? 
https://cortexmetrics.io/

BR

Andre Martins

**Comment by ArchiFleKs** [comment]
Hi and thanks for the feedback :)

For now we just implemented thanos which was not that easy. I'll have to have a look on how cortex works, I hear it is more complicated than thanos. 

But it is just a matter of time. We are of course open to PR on this project

**Comment by apmartins85** [comment]
Cool.. I started something related to cortex .. [wip](https://github.com/particuleio/terraform-kubernetes-addons/pull/20)
