### ISSUE TITLE
[bug] External-dns addon crashes TF during preparing a plan

### ISSUE THREAD

**Issue by dejwsz** [particuleio/terraform-kubernetes-addons#192]
## Describe the bug

I have a problem with adding external-dns add-on. There is such error during creating a plan in Terraform:

Error: Error in function call
│
│   on .terraform/modules/eks-aws-addons/modules/aws/external-dns.tf line 3, in locals:
│    3:   external-dns = { for k, v in var.external-dns : k => merge(
│    4:     local.helm_defaults,
│    5:     {
│    6:       chart                     = local.helm_dependencies[index(local.helm_dependencies.*.name, "external-dns")].name
│    7:       repository                = local.helm_dependencies[index(local.helm_dependencies.*.name, "external-dns")].repository
│    8:       chart_version             = local.helm_dependencies[index(local.helm_dependencies.*.name, "external-dns")].version
│    9:       name                      = k
│   10:       namespace                 = k
│   11:       service_account_name      = "external-dns"
│   12:       enabled                   = false
│   13:       create_iam_resources_irsa = true
│   14:       iam_policy_override       = null
│   15:       default_network_policy    = true
│   16:     },
│   17:     v,
│   18:   ) }
│     ├────────────────
│     │ local.helm_defaults is object with 16 attributes
│     │ local.helm_dependencies is tuple with 32 elements
│
│ Call to function "merge" failed: arguments must be maps or objects, got
│ "bool".
╵

## What is the current behavior?
Terraform exits with error while creating a plan.

## How to reproduce? Please include a code sample if relevant.
Try to add external-dns using such versions of deps:

provider "registry.terraform.io/fluxcd/flux" {
  version     = "0.1.4"
}

provider "registry.terraform.io/gavinbunney/kubectl" {
  version     = "1.10.0"
}

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.38.0"
}

provider "registry.terraform.io/hashicorp/helm" {
  version     = "2.1.2"
}

provider "registry.terraform.io/hashicorp/http" {
  version = "2.1.0"
}

provider "registry.terraform.io/hashicorp/kubernetes" {
  version     = "2.1.0"
}

provider "registry.terraform.io/hashicorp/local" {
  version     = "2.1.0"
}

provider "registry.terraform.io/hashicorp/null" {
  version     = "3.1.0"
}

provider "registry.terraform.io/hashicorp/random" {
  version     = "3.1.0"
}

provider "registry.terraform.io/hashicorp/template" {
  version     = "2.2.0"
}

provider "registry.terraform.io/hashicorp/time" {
  version = "0.7.1"
}

provider "registry.terraform.io/hashicorp/tls" {
  version = "3.1.0"
}

provider "registry.terraform.io/integrations/github" {
  version     = "4.9.2"
}

## What's the expected behavior?
External-dns add-on shown in a plan and later deployed with apply.

## Environment details

* Affected module version: 2.0.0
* OS: macos 11.3.1
* Terraform version: 0.15.1
* Kubernetes version: 1.19.8

**Comment by ArchiFleKs** [comment]
@dejwsz can you show me the variable, if using external DNS on AWS the syntax is the following:

```
  external-dns = {
    external-dns = {
      enabled = true
    },
  }
```
As you ccan deploy multiple external-dns chart (for example if you want to do a split view DNS)

Example are available [here](https://github.com/particuleio/teks/blob/main/terragrunt/live/demo/eu-west-3/clusters/full/eks-addons/terragrunt.hcl)

Or [here](https://github.com/particuleio/teks/blob/main/terraform/live/demo/eu-west-3/clusters/full/eks-addons/main.tf#L86) with Terraform

I believe this will fix your issue

**Comment by dejwsz** [comment]
Yes indeed, my fault then. It works now. Thank you!
