### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by bnayah** [particuleio/terraform-kubernetes-addons#198]
## Describe the bug

Url for prometheus-adapter is broken.

## What is the current behavior?
Port should not be appended to the url.
The helm chart appends the port to the url [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/templates/deployment.yaml#L54)

## How to reproduce? Please include a code sample if relevant.
Simply install a cluster with kube-prometheus-stack and prometheus-adapter. Prometheus-adapter will have the port appended twice:
--prometheus-url=http://kube-prometheus-stack-prometheus.monitoring.svc:9090:9090

Custom metrics will get a 404. Upon editing the deployment and removing the redundant ":9090", the prometheus-adapter functions properly again.

## What's the expected behavior?
The url should not include the port, as the port is a separate variable in the upstream helm chart and is templated by the upstream helm chart.

## Are you able to fix this problem and submit a PR? Link here if you have already.
I will create a PR

## Environment details

* Affected module version: 2.0.0
* OS: Mac OS 11.2.3
* Terraform version: 0.14.10
* Kubernetes version: 1.19.6

**Comment by ArchiFleKs** [comment]
Don't worry @bnayah it is a quick fix, will release now
