### ISSUE TITLE
feature: CloudWatch Container Insights agent, would the project be open to a PR?

### ISSUE THREAD

**Issue by mattsimonsen** [particuleio/terraform-kubernetes-addons#22]
Hello,

This is a great project!

If I contributed code for AWS CloudWatch Container Insights support as an additional module, would you be open to including this in Terraform Kubernetes Addons ?

Currently I am using https://registry.terraform.io/modules/Young-ook/eks/aws/latest/submodules/container-insights but would love to have it integrated into this project.  I would be willing to do the work to put the code together and submit a PR if you're willing to consider having it included. 

Before I start, I would like to know that you are open to including it. What do you think?

Thanks,
Matt

**Comment by ArchiFleKs** [comment]
Hi, thanks for your first issue. We are of course open to include it if you are willing to do a PR ;)

**Comment by mattsimonsen** [comment]
It might take me some time, but this is on my "todo" list.

Thanks!

**Comment by tomstockton** [comment]
I'd like to use this feature as well. Note there is an official chart that can be used to install the Cloudwatch insights agent.

https://github.com/aws/eks-charts/tree/master/stable/aws-cloudwatch-metrics.

@mattsimonsen @ArchiFleKs can we leave this issue open please so I can track its status?

I might even offer a PR myself if I get time!

**Comment by mattsimonsen** [comment]
Thanks for the feedback, I'd also like to get this in place and intend to get a PR at some point.

**Comment by ArchiFleKs** [comment]
Hi, I'm planning to integrate more AWS component such as SSM agent and the missing container insight components

Correct me if I'm wrong but container insight is not a software component ? 

It is just the deployment of:
* fluent-bit logs to cloudwatch (already implemented here)
* cloudwatch agent to export metrics to cloudwatch

**Comment by tomstockton** [comment]
Hi @ArchiFleKs - I also just wanted to echo the comments of @mattsimonsen earlier, this is a great project so thanks for maintaining it!

Not sure on the definition of 'software component' but yes, you're right, it's just deploying k8s resources to the cluster. I'm already using the fluent-bit logs addon (works nicely thanks!) and it looks like the cloudwatch agent to export the metrics is very similar if you look at the chart linked above - daemonset, rbac, configmap.

**Comment by ArchiFleKs** [comment]
Thanks, there is some work to be done on the `eks-charts` charts before including them because most of them, and cloudwatch agent do not support basic feature la priority classes and taint/toleration which is a must have to include them here.

**Comment by ArchiFleKs** [comment]
@mattsimonsen any reason for closing this ?

**Comment by mattsimonsen** [comment]
@ArchiFleKs I had forgotten about it, when I saw it I figured that I'd clean it up. If you prefer it open, I'm good with that :-)
