### ISSUE TITLE
[bug] gavinbunney/kubectl with Kubernetes 1.27 causes Error: ... failed to fetch resource from kubernetes: the server could not find the requested resource

### ISSUE THREAD

**Issue by gpooleoneiro** [particuleio/terraform-kubernetes-addons#2458]
Kubernetes version 1.27 with gavinbunney/kubectl provider occasionally causes error on kubectl_manifest resources.

This issue is outlined by this github issue:
https://github.com/gavinbunney/terraform-provider-kubectl/issues/270

Suggested fix:
Migrate to alekc/kubectl provider where a fix has been implemented and is being maintained.
gavinbunney/kubectl provider is now a dead repo and isn't being maintained.

**Comment by ArchiFleKs** [comment]
Should be fixed by #2557
