### ISSUE TITLE
[bug] Karpenter v1beta1 api's do not work with current configured settings

### ISSUE THREAD

**Issue by gpooleoneiro** [particuleio/terraform-kubernetes-addons#2490]
Affected module: Karpenter

As mentioned in the following github thread https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2733

The IAM role created when running this module (KarpenterIRSA-...) is missing the key IAM role iam:GetInstanceProfile. Preventing karpenter from creating any new nodes.

To fix this I would suggest either manually adding the role to the list of additional policies that you add to KarpenterIRSA https://github.com/particuleio/terraform-kubernetes-addons/blob/04d4af91e3352be2f1e97fcdbad9e0a369370f71/modules/aws/karpenter.tf#L40

Or by adding the following flag (as stated in the github issue linked at the top of the page) when calling terraform-aws-eks/module/karpenter 
enable_karpenter_instance_profile_creation=True
https://github.com/particuleio/terraform-kubernetes-addons/blob/04d4af91e3352be2f1e97fcdbad9e0a369370f71/modules/aws/karpenter.tf#L69

**Comment by ArchiFleKs** [comment]
@gpooleoneiro Hi thanks for the heads-up, could you do the PR ? Otherwise I'll take care of it whenever I can

**Comment by ArchiFleKs** [comment]
Fixed upstream
