### ISSUE TITLE
[enhancement] Update aws load balancer controller policy

### ISSUE THREAD

**Issue by PaulKushch** [particuleio/terraform-kubernetes-addons#3091]
It seems that `ec2:GetSecurityGroupsForVpc` is also needed for aws load balancer controller. Can `aws-load-balancer-controller` policy be updated?

Like here https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/commit/dfef351722163fc20212291db5025dc62a2d2ec0 

 Best regards

**Comment by ArchiFleKs** [comment]
Thanks this was fixed in https://github.com/particuleio/terraform-kubernetes-addons/commit/3142c38c2e685007bd667d626bb3f8be4aaa1671
