### ISSUE TITLE
[bug] 'kong' install via helm_release does not create 'kong' ingressclass

### ISSUE THREAD

**Issue by flaupretre** [particuleio/terraform-kubernetes-addons#621]
## Describe the bug

After deploying kong on a cluster via terraform-kubernetes-addons, everything seems to be OK (ingress controller is created and looks fine) but the 'kong 'ingressclass' does not exist. The, ingress creation fails when they try to reference the unexisting 'kong' ingress class.

After deploying the same version of the kong chart using the helm CLI, a 'kong' ingressclass exists and subsequent ingress object creation succeeds.

To reproduce : 
Using module version 2.15.1 with an EKS cluster v 1.21.

configuration is : 
```hcl
  kong = {
    enabled = true
    chart_version = "2.6.1"
    extra_values = <<-EXTRA_VALUES
      autoscaling:
        enabled: true
        minReplicas: ${var.cfg.addons.kong.minReplicas}
    EXTRA_VALUES
  }
```
Workaround: I created a 'kong' ingressclass containing 'controller: konghq.com/ingress-controller' and I am currently testing if ingresses work with this configuration but AFAIK, it cannot be the right solution as helm CLI does not require to create this object manually.

Investigating in the helm chart, I see that my 'ingressVersion' is 'extensions/v1beta1' (deprecated) when it should be 'networking.k8s.io/v1'. It means that '(.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress")' returns false when executed via an helm_release and true when executed by the helm CLI (should be true because 'kubectl api-resources | grep Ingress' shows an 'Ingress' resource in 'networking.k8s.io/v1').

Did someone already meet (and fix) this problem ? I am not sure we can do something at this level because, AFAIK, we cannot control what '.Capabilities.APIVersions' is doing.

**Comment by ArchiFleKs** [comment]
Not sure about this, I know other charts use this also and I never had any issue with creating ingress v1 when neeed but I do not use kong, it might be du to the way the charts is coded i'll have a look when I can, but for example, `kube-prometheus-stack` do it this way: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L137

**Comment by flaupretre** [comment]
It's quite strange. I split my cluster install procedure to several terraform calls instead of a single one and the problem is gone. Maybe a side effect of another install running in parallel or some unidentified dependency. Something may also need time to initialize (like operators and CSVs). Anyway, thanks for your reply.
