### ISSUE TITLE
Invalid URL for thanos replicate dashboard

### ISSUE THREAD

**Issue by wyrie** [particuleio/terraform-kubernetes-addons#65]
https://github.com/particuleio/terraform-kubernetes-addons/blob/d954b2961756e92d69ab3ae7122f4909dd6c40af/modules/aws/kube-prometheus.tf#L243

Found the dashboard at
`https://raw.githubusercontent.com/thanos-io/thanos/master/examples/dashboards/bucket_replicate.json`

**Comment by tbobm** [comment]
Hi !

Thank you for reporting this error, it will be fixed shortly.

Best regards,
