### ISSUE TITLE
Creation of duplicate IAM policy for thanos bucket

### ISSUE THREAD

**Issue by wyrie** [particuleio/terraform-kubernetes-addons#66]
https://github.com/particuleio/terraform-kubernetes-addons/blob/d954b2961756e92d69ab3ae7122f4909dd6c40af/modules/aws/thanos.tf#L227

Only create the policy if create_bucket is done in thanos.tf

`count = local.thanos["enabled"] && local.thanos["create_bucket"] && local.thanos["create_iam_resources_irsa"] ? 1 : 0`

**Comment by tbobm** [comment]
Hello again,

Thank you for providing another correction. As for issue #65 , this will be fixed shortly.

Best regards,

**Comment by ArchiFleKs** [comment]
This is not a duplicate policy. If prometheus is creating the S3 bucket, Thanos component still need access to it, like compactor and storage gateway. So this policy is needed and not a duplicate. This allow to plug thanos to an existing bucket (like the kube-prometheus one)  or to create a bucket directly in thanos and plus kube-prometheus on it (you can do it in any way you want).

Our default configuration is to create the bucket in prometheus and plug thanos on it.

fixes will be revert: https://github.com/particuleio/terraform-kubernetes-addons/pull/69
