### ISSUE TITLE
[bug] cert-manager prometheus dashboard doesn't work

### ISSUE THREAD

**Issue by rguichard** [particuleio/terraform-kubernetes-addons#71]
## Describe the bug

The cert-manager dashboard on Prometheus doesn't work, there is no data because datasource cannot be found.

## What is the current behavior?

No data

![image](https://user-images.githubusercontent.com/9936825/110965613-a4c81680-8354-11eb-8023-de892583c5a2.png)

## How to reproduce? Please include a code sample if relevant.

Deploy kubernetes-addons (`1.27.1`) with cert-manager and kube-prometheus-stack enabled.

## What's the expected behavior?

Data ^^

## Environment details

* Affected module version: 1.27.1
* OS: Linux
* Terraform version: 0.14.7
* Kubernetes version: 1.20.4

**Comment by ArchiFleKs** [comment]
the data source issue have been fixed in AWS but not elsewhere: https://github.com/particuleio/terraform-kubernetes-addons/blob/main/modules/aws/kube-prometheus.tf#L172

I'll make the PR
