### ISSUE TITLE
[aws-ebs-csi-driver] - Helm Chart does not support to create VolumeSnapshotClass

### ISSUE THREAD

**Issue by fsakget** [particuleio/terraform-kubernetes-addons#807]
Actually Helm Chart does not support to create kind: VolumeSnapshotClass  (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1146)

https://github.com/particuleio/terraform-kubernetes-addons/blob/50c5c59d7042580e5e305ecbb1b0222f713a1d66/modules/aws/aws-ebs-csi-driver.tf#L31

eks-addons-critical$ terragrunt apply

│ Error: Failed to determine GroupVersionResource for manifest
│ 
│   with kubernetes_manifest.aws-ebs-csi-driver_vsc[0],
│   on aws-ebs-csi-driver.tf line 216, in resource "kubernetes_manifest" "aws-ebs-csi-driver_vsc":
│  216: resource "kubernetes_manifest" "aws-ebs-csi-driver_vsc" {
│ 
│ no matches for kind "VolumeSnapshotClass" in group
│ "snapshot.storage.k8s.io"
╵
ERRO[0016] 1 error occurred:
        * exit status 1

**Comment by ArchiFleKs** [comment]
Hi @fsakget this a known bug, even though [this](https://github.com/particuleio/terraform-kubernetes-addons/blob/main/modules/aws/aws-ebs-csi-driver.tf#L216) depends on the CRDs it still try to plan it before and there fore fail. One solution is to put `volume_snapshot_class = null` apply and the remove the line and re apply.

I'm trying to find another workaround for this to work

**Comment by ArchiFleKs** [comment]
@fsakget this will be fixed in next release

**Comment by ArchiFleKs** [comment]
@fsakget this is fixed in `4.0.0` release
