### ISSUE TITLE
[warning]  Argument is deprecated in aws s3 bucket lifecycle

### ISSUE THREAD

**Issue by dejwsz** [particuleio/terraform-kubernetes-addons#957]
## Describe the bug
```
Warning: Argument is deprecated
│
│   with module.eks_addons.module.eks-aws-addons.module.kube-prometheus-stack_thanos_bucket.aws_s3_bucket.this,
│   on .terraform/modules/eks_addons.eks-aws-addons.kube-prometheus-stack_thanos_bucket/main.tf line 7, in resource "aws_s3_bucket" "this":
│    7: resource "aws_s3_bucket" "this" {
│
│ Use the aws_s3_bucket_lifecycle_configuration resource instead
│
│ (and 43 more similar warnings elsewhere)
```
## What is the current behavior?
Warnings related to depracated s3 bucket lifecycle settings are shown

## How to reproduce? Please include a code sample if relevant.
Use the latest aws terraform module (registry.terraform.io/hashicorp/aws = 3.75.1)

## What's the expected behavior?
No warnings like that, this can break things in future.

**Comment by ArchiFleKs** [comment]
@dejwsz I think this was deprecated in AWS provider v4. The issue is with https://github.com/terraform-aws-modules/terraform-aws-s3-bucket which is used by this module. I think they left it this way for now as it is just deprecated and they allow provider < 4.0

**Comment by dejwsz** [comment]
The case is it is even depracated for version < 4.0: https://github.com/hashicorp/terraform-provider-aws/pull/23445
So sooner or later it should be done I think. Anyway looks like it is not that hard to refactor.

**Comment by ArchiFleKs** [comment]
@dejwsz This module should picked up the S3 module when one of these PR is merged: 

https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pulls

Please feel free to reopen if needed, and thanks for taking the time to open an issue

**Comment by dejwsz** [comment]
OK I see, it is a matter of time then, thanks!
