### ISSUE TITLE
[bug] - License?

### ISSUE THREAD

**Issue by mkuendig** [particuleio/terraform-kubernetes-addons#962]
## Describe the bug

Thanks a lot folks for publishing all these submodules for Kubernetes. This is great stuff. Can you please clarify which license this is offered under?

## What is the current behavior?

No license added, so unsure what license this falls under

## How to reproduce? Please include a code sample if relevant.

If this is opensource, please add for example the apache license from here: https://www.apache.org/licenses/LICENSE-2.0

## What's the expected behavior?

If opensource a license file should be added.

## Environment details

* Affected module version:
* OS:
* Terraform version:
* Kubernetes version

**Comment by ArchiFleKs** [comment]
@mkuendig they should all be apache2 license. I'll add it to the repo. Feel free to reuse and adapt, and give some credit if possible

**Comment by mkuendig** [comment]
excellent. thank you so much!
